baseURL = "https://pepabo.github.io/alive-project-obs-plugins/"
languageCode = "ja"
title = "ストリーマーマガジン｜配信者を応援するWebメディア"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
